# Generated by Django 5.2.7 on 2025-11-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_kinesiologist_delete_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinesiologist',
            name='email',
        ),
    ]
