# Generated by Django 5.2.7 on 2025-11-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_kinesiologist_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinesiologist',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
